import AppKit
import Carbon.HIToolbox

extension NSPasteboard.PasteboardType {
    static let portalMarker = NSPasteboard.PasteboardType("com.martyvasquez.portal.marker")
    // nspasteboard.org conventions used by password managers and other clipboard tools.
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

/// Polls the pasteboard (macOS has no change notification) and records new copies.
@MainActor
final class ClipboardMonitor {
    private let store: ClipStore
    private let settings: SettingsStore
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?
    var paused = false
    /// Until then, changes are Portal's own (reading a selection with ⌘C) and aren't recorded.
    private static var ignoreUntil = Date.distantPast

    static func ignoreChanges(for seconds: TimeInterval) {
        ignoreUntil = Date().addingTimeInterval(seconds)
    }

    init(store: ClipStore, settings: SettingsStore) {
        self.store = store
        self.settings = settings
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        guard !paused, Date() >= Self.ignoreUntil else { return }
        capture(pb)
    }

    private func capture(_ pb: NSPasteboard) {
        let types = Set(pb.types ?? [])
        if types.contains(.portalMarker) || types.contains(.transient) || types.contains(.autoGenerated) { return }

        let v = settings.values
        let front = NSWorkspace.shared.frontmostApplication
        if let id = front?.bundleIdentifier, v.ignoredBundleIDs.contains(id) { return }

        var p = ClipPayload(machineID: settings.machineID, machineName: settings.machineName, kind: .text, hash: "")
        p.sourceApp = front?.localizedName
        p.sourceBundleID = front?.bundleIdentifier

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            p.kind = .files
            p.files = urls.map(\.path)
            p.hash = Crypto.sha256(Data(p.files!.joined(separator: "\n").utf8))
        } else if let s = pb.string(forType: .string),
                  !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard s.utf8.count <= 2_000_000 else { return }
            p.kind = Self.isURL(s) ? .url : .text
            p.text = s
            p.isSecret = types.contains(.concealed) || SecretDetector.looksSecret(s)
            if !p.isSecret, v.cleanTerminalCopies, let id = p.sourceBundleID, TerminalText.terminalBundleIDs.contains(id) {
                let cleaned = TerminalText.clean(s, unwrap: v.unwrapTerminalLines)
                if cleaned != s, !cleaned.isEmpty {
                    p.text = cleaned
                    p.originalText = s
                    // Swap the cleaned text onto the clipboard so a plain ⌘V gets it.
                    pb.clearContents()
                    pb.setString(cleaned, forType: .string)
                    lastChange = pb.changeCount
                }
            }
            p.hash = Crypto.sha256(Data((p.text ?? s).utf8))
        } else if let (png, w, h) = Self.imageData(pb) {
            guard png.count <= v.maxImageMB * 1_048_576 else { return }
            p.kind = .image
            p.image = png
            p.imageWidth = w
            p.imageHeight = h
            p.hash = Crypto.sha256(png)
        } else {
            return
        }
        if p.isSecret && !v.recordSecrets { return }
        store.add(p)
    }

    private static func isURL(_ s: String) -> Bool {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.contains(where: \.isWhitespace), let url = URL(string: t), let scheme = url.scheme else { return false }
        return ["http", "https"].contains(scheme.lowercased()) && url.host != nil
    }

    private static func imageData(_ pb: NSPasteboard) -> (Data, Int, Int)? {
        let raw = pb.data(forType: .png) ?? pb.data(forType: .tiff)
        guard let raw, let rep = NSBitmapImageRep(data: raw) else { return nil }
        let png = pb.data(forType: .png) ?? rep.representation(using: .png, properties: [:])
        guard let png else { return nil }
        return (png, rep.pixelsWide, rep.pixelsHigh)
    }
}

enum SecretDetector {
    private static let patterns: [NSRegularExpression] = [
        #"^sk-[A-Za-z0-9_\-]{20,}$"#,                       // OpenAI / Anthropic
        #"^(sk|pk|rk)_(live|test)_[A-Za-z0-9]{16,}$"#,      // Stripe
        #"^gh[pousr]_[A-Za-z0-9]{30,}$"#,                   // GitHub
        #"^github_pat_[A-Za-z0-9_]{40,}$"#,
        #"^glpat-[A-Za-z0-9_\-]{20,}$"#,                    // GitLab
        #"^(AKIA|ASIA)[0-9A-Z]{16}$"#,                      // AWS
        #"^xox[abposr]-[A-Za-z0-9\-]{10,}$"#,               // Slack
        #"^AIza[0-9A-Za-z_\-]{35}$"#,                       // Google
        #"^SG\.[A-Za-z0-9_\-]{16,}\.[A-Za-z0-9_\-]{16,}$"#, // SendGrid
        #"^npm_[A-Za-z0-9]{36}$"#,
        #"^eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}$"#, // JWT
    ].compactMap { try? NSRegularExpression(pattern: $0) }

    static func looksSecret(_ s: String) -> Bool {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard t.count >= 16, t.count <= 10_000 else { return false }
        if t.contains("-----BEGIN") && t.contains("PRIVATE KEY-----") { return true }
        guard !t.contains(where: \.isWhitespace) else { return false }
        let range = NSRange(t.startIndex..., in: t)
        if patterns.contains(where: { $0.firstMatch(in: t, range: range) != nil }) { return true }
        return looksLikeRandomToken(t)
    }

    /// Long single token with mixed case + digits and high entropy (not a URL or path).
    private static func looksLikeRandomToken(_ t: String) -> Bool {
        guard (32...200).contains(t.count), !t.contains("://"), !t.hasPrefix("/"), !t.hasPrefix("~") else { return false }
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_-+/=."))
        guard t.unicodeScalars.allSatisfy({ allowed.contains($0) && $0.isASCII }) else { return false }
        guard t.contains(where: \.isUppercase), t.contains(where: \.isLowercase), t.contains(where: \.isNumber) else { return false }
        var counts: [Character: Int] = [:]
        for c in t { counts[c, default: 0] += 1 }
        let n = Double(t.count)
        let entropy = counts.values.reduce(0.0) { acc, c in
            let p = Double(c) / n
            return acc - p * log2(p)
        }
        return entropy >= 4.0
    }

    static func mask(_ s: String) -> String {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if t.contains("PRIVATE KEY") { return "Private key ••••••••" }
        guard t.count > 12 else { return String(repeating: "•", count: 10) }
        return "\(t.prefix(4))••••••••\(t.suffix(4))"
    }
}

@MainActor
enum Paster {
    static func write(_ clip: Clip, original: Bool = false) {
        let pb = NSPasteboard.general
        pb.clearContents()
        let p = clip.payload
        switch p.kind {
        case .text:
            pb.setString((original ? p.originalText : nil) ?? p.text ?? "", forType: .string)
        case .url:
            pb.setString(p.text ?? "", forType: .string)
            pb.setString(p.text ?? "", forType: .URL)
        case .image:
            if let png = p.image {
                pb.setData(png, forType: .png)
                if let tiff = NSImage(data: png)?.tiffRepresentation { pb.setData(tiff, forType: .tiff) }
            }
        case .files:
            pb.writeObjects((p.files ?? []).map { URL(fileURLWithPath: $0) as NSURL })
        }
        pb.setData(Data(), forType: .portalMarker)
        if p.isSecret { pb.setData(Data(), forType: .concealed) }
    }

    /// Sends ⌘V to whatever app is frontmost. Needs Accessibility permission.
    static func sendPaste() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let v = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}
